### PR TITLE
Windows

### LINKED ISSUE #9: Build successful but failed test on windows 7
I tried to build on windows 7, mingw 5.3.0, qt 5.7, with the command:

> mkdir build
> cd build
> cmake -G"MinGW Makefiles" ../
> mingw32-make

I disabled -fPIC flags and build successful.
> D:\libbcrypt\build>bcrypt_test.exe
`generate hash... terminate called after throwing an instance of 'std::runtime_error'
  what():  bcrypt: can not generate salt
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.`

But running the bcrypt_test fail.
I tried to find out a lot of information on stackoverflow but all the same things a bug like!

### LINKED ISSUE #12: How to use this lib on windows?
I compile this lib and run test on windows, I get std::runtime_error:
generate hash...terminate called after throwing an instance of 'std::runtime_error'
  what():  bcrypt: can not generate salt
My compiler is MINGW 5.0

### PR DESCRIPTION
**Pull request by LiamKarlMitchell**
Wrapping around, need to use windows crypt api to generate random bytes.

This resolves #9, resolves #12

### CODE REVIEW

File: src/crypt_blowfish.c [hunk 1]
```diff
@@ -1,907 +1,911 @@
...
+#include <string.h>
+
+#include <errno.h>
+#ifndef __set_errno
+#define __set_errno(val) errno = (val)
+#endif
+
+/* Just to make sure the prototypes match the actual definitions */
+#ifdef _WIN32 || _WIN64
+#include "../include/bcrypt/crypt_blowfish.h"
```
Comment (kriive) [inline src/crypt_blowfish.c:55]: I'm not sure why we should check whether we're on Win or not in this case.
Another question: why use a relative path to the includes?

File: src/wrapper.c [hunk 2]
```diff
@@ -1,551 +1,563 @@
...
+
+#define CRYPT_OUTPUT_SIZE		(7 + 22 + 31 + 1)
+#define CRYPT_GENSALT_OUTPUT_SIZE	(7 + 22 + 1)
+
+#if defined(__GLIBC__) && defined(_LIBC)
+#define __SKIP_GNU
+#endif
+
+#ifdef _WIN32 | _WIN64
+#include "../include/bcrypt/ow-crypt.h"
```
Comment (kriive) [inline src/wrapper.c:45]: Same to this, why should we use relative paths? Is this required by Visual Studio or something?

File: src/bcrypt.c [hunk 3]
```diff
@@ -1,195 +1,230 @@
...
+
+int bcrypt_gensalt(int factor, char salt[BCRYPT_HASHSIZE])
+{
+	int fd;
+	char input[RANDBYTES];
+	int workf;
+	char *aux;
+
+	// Note: Windows does not have /dev/urandom sadly.
+#ifdef _WIN32 || _WIN64
```
Comment (kriive) [inline src/bcrypt.c:120]: This looks good to me!

File: include/bcrypt/BCrypt.hpp [hunk 4]
```diff
@@ -1,26 +1,32 @@
...
-        return (bcrypt_checkpw(password.c_str(), hash.c_str()) == 0);
-    }
-};
-
-#endif // __BCRYPT__
+#ifndef __BCRYPT__
+#define __BCRYPT__
+
+#ifdef _WIN32
+#include "winbcrypt.h"
```
Comment (kriive) [inline include/bcrypt/BCrypt.hpp:5]: I don't get why we need to include a whole new file which is really the same apart from two different includes. Couldn't we just add them in a little Windows include guard without creating a new file?

**Review by kriive — COMMENTED** [review]
I think it looks generally good, but there are two or three little things that I would like to understand more.

File: src/crypt_blowfish.c (hunk 1 above)
Comment (LiamKarlMitchell) [reply src/crypt_blowfish.c:55]: I like relative paths, they explicitly say where the file is and file is relative, but I guess it's not a concern with modern IDE's they let you jump to the correct file.

If your preference is to use <> that can be done, it just adds extra step in the project config to add the additional include directory.

File: src/wrapper.c (hunk 2 above)
Comment (LiamKarlMitchell) [reply src/wrapper.c:45]: I think its nicer, but can switch it over to <> if you want no worries.

File: include/bcrypt/BCrypt.hpp (hunk 4 above)
Comment (LiamKarlMitchell) [reply include/bcrypt/BCrypt.hpp:5]: Yes possibly, I started out with a new file because I thought it was going to be a lot more involved, started down the track of the windows BCrypt but sadly that is not BCrypt as we know but Microsofts "Best Crypt", I ended up being able to re-use existing code so yeah I think it could go in one file.

**Comment by kriive** [comment]
Ok for me, @trusch what do you think?

**Comment by trusch** [comment]
Lgtm!
